name: PrayerTime
description: A Dart Pacakge to get prayer times of different loctions based on geo and timezone.
version: 1.0.0
homepage: https://lablnet.github.io/

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
